# FreeRDP: 自定义业务DVC虚拟通道配置选项

set(OPTION_DEFAULT ON)
set(OPTION_CLIENT_DEFAULT ON)
set(OPTION_SERVER_DEFAULT OFF)

define_channel_options(
  NAME
  "rdp2vir"
  TYPE
  "dynamic"
  DESCRIPTION
  "RDP2VIR Custom Business DVC Virtual Channel (mytest)"
  SPECIFICATIONS
  ""
  DEFAULT
  ${OPTION_DEFAULT}
  CLIENT_DEFAULT
  ${OPTION_CLIENT_DEFAULT}
  SERVER_DEFAULT
  ${OPTION_SERVER_DEFAULT}
)
